PROGRAM SANDBED
real*8,parameter:: Pi = 3.141592653589793238462643383279502884
! how many particle
integer,parameter::NPAR = 80
INTEGER M,NN,J
REAL*8 LX_DOMAIN,LY_DOMAIN,LZ_DOMAIN,SPC(NPAR,3)
REAL*8 DISP,RAN2,RRR,SPD

OPEN(1,FILE='SPC.DAT')
! domain scheme
LX_DOMAIN=3.0D0*Pi
LY_DOMAIN=6.0D0*Pi
LZ_DOMAIN=3.0D0*Pi
! D
SPD=1.D0

DO M=1,NPAR
1   CALL RANDOM_NUMBER(RRR)
    SPC(M,1)=(LX_DOMAIN-SPD)*RRR+RADIUS*SPD
    CALL RANDOM_NUMBER(RRR)
    SPC(M,2)=(LY_DOMAIN-SPD)*RRR+RADIUS*SPD
    CALL RANDOM_NUMBER(RRR)
    SPC(M,3)=(LZ_DOMAIN-SPD)*RRR+RADIUS*SPD
! 1   SPC(M,1)=(LX_DOMAIN-SPD)*RAN2(RRR)+0.5D0*SPD
!     SPC(M,2)=(LY_DOMAIN-SPD)*RAN2(RRR)+0.5D0*SPD
!     SPC(M,3)=(LZ_DOMAIN-SPD)*RAN2(RRR)+0.5D0*SPD
    DO NN=1,M-1
        DISP=SQRT((SPC(M,1)-SPC(NN,1))**2.D0+(SPC(M,2)-SPC(NN,2))**2.D0+ &
            (SPC(M,3)-SPC(NN,3))**2.D0)
        IF(DISP.LE.1.2D0*SPD) GOTO 1
    ENDDO
    print*,'complete',M
    !write(*,*) M,SPC(M,1),SPC(M,2),SPC(M,3)
ENDDO

!IF(MYID.EQ.0) THEN
DO M=1,NPAR
    WRITE(1,*) SPC(M,1),SPC(M,2),SPC(M,3)
ENDDO
!ENDIF
END

FUNCTION RAN2(RRR) 
REAL*8 SSS, UUU, VVV, RRR, RAN2
INTEGER MMM
SSS=65536.D0
UUU=2053.D0
VVV=13849.D0
MMM=RRR/SSS
RRR=RRR-MMM*SSS
RRR=UUU*RRR+VVV
MMM=RRR/SSS
RRR=RRR-MMM*SSS
RAN2=RRR/SSS
RETURN
END
